Validate that the correct doctl auth context has been selected before spawning droplet

diff --git a/lib/create-machine-digitalocean b/lib/create-machine-digitalocean
--- a/lib/create-machine-digitalocean
+++ b/lib/create-machine-digitalocean
@@ -34,9 +34,15 @@ fi
 
 if [ "$MACHINE_DO_AUTH_CONTEXT" != "" ]; then
     if [ "$(doctl auth list | grep -c $MACHINE_DO_AUTH_CONTEXT)" == "0" ]; then
-        exit "error: machine.do_auth_context specifies unknown auth context \"$MACHINE_DO_AUTH_CONTEXT\""
+        echo "error: machine.do_auth_context specifies unknown auth context \"$MACHINE_DO_AUTH_CONTEXT\"" >&2
         exit 1
     fi
+    doctl auth switch --context $MACHINE_DO_AUTH_CONTEXT >&2 | grep -v "Now using context"
+    if [ "$(doctl auth list | grep '(current)' | grep -c $MACHINE_DO_AUTH_CONTEXT)" == "0" ]; then
+        echo "error: failed to set machine.do_auth_context (\"$MACHINE_DO_AUTH_CONTEXT\") as the current auth context" >&2
+        exit 1
+    fi
+
 fi
 
 echo "Will spawn droplet using auth context: $(doctl auth list | grep current)" >&2
